version: '3'

services:

  app-test:
    build:
      context: .
      dockerfile: ./services/unittesting/Dockerfile
    command: ["pytest", "-n", "auto", "--asyncio-mode=auto", "--cov=.", "--cov-report=xml", "--cov-report=term-missing"]
