version: "3.9"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - ~/.dev.env
    #environment:
     # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      zenml-services-network:
        ipv4_address: 192.168.1.25
  zenml:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    env_file:
      - ~/.dev.env
    #environment:
     # - ZENML_STORE_URL=${ZENML_STORE_URL}
      #- ZENML_DEFAULT_USER_NAME=${ZENML_DEFAULT_USER_NAME}
      #- ZENML_DEFAULT_USER_PASSWORD=${ZENML_DEFAULT_USER_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      zenml-services-network:
        ipv4_address: 192.168.1.20
    restart: on-failure

networks:
  zenml-services-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
